version: '2.1'

services:
    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        image: af
        container_name: af-compose
        restart: always
        environment:
            - SERVICE_ACCOUNT_JSON
            - SERVICE_ACCOUNT_KEY
            - DATABASE_COPY_URL
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN
            - AIRFLOW__WEBSERVER__WEB_SERVER_PORT
        ports:
            - "5000:5000"
        command: webserver
        volumes:
            - ./app_home:/app