version: '2.1'

services:
    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        image: af
        container_name: af-compose
        restart: always
        environment:
            - SERVICE_ACCOUNT_JSON
            - SERVICE_ACCOUNT_KEY
            - DATABASE_COPY_URL
        ports:
            - "8080:8080"
        command: webserver
        volumes:
            - ./app_home:/app